// Generates src/styles/tokens.css from src/lib/designTokens.ts.
// Run: node scripts/generate-tokens.mjs  (also runs automatically before `next dev`/`next build`)

import { writeFileSync } from "node:fs";
import { designTokens } from "../src/lib/designTokens.ts";

const lines = [
  "/* GENERATED by scripts/generate-tokens.mjs from src/lib/designTokens.ts. Do not edit by hand. */",
  ":root {",
  `  --color-bg: ${designTokens.bg};`,
  `  --color-bg-muted: ${designTokens.bgMuted};`,
  `  --color-ink: ${designTokens.ink};`,
  `  --color-ink-muted: ${designTokens.inkMuted};`,
  `  --color-line: ${designTokens.line};`,
  `  --color-edge: ${designTokens.edge};`,
  ...designTokens.pastels.map((hex, i) => `  --color-pastel-${i + 1}: ${hex};`),
  "}",
  "",
];

writeFileSync(new URL("../src/styles/tokens.css", import.meta.url), lines.join("\n"));
console.log(`tokens.css written (${designTokens.pastels.length} pastels)`);
