-- Phase 4: the "live" half of each person, plus account claiming.
-- Run this once in the Supabase SQL editor (or `supabase db push`), then run
-- supabase/seed.sql (generated by `npm run data:seed-sql`).

create table public.people (
  id         text primary key,                      -- same slug as data/people.json
  email      text unique,                           -- join key for claiming; stored lowercase
  owner_uid  uuid unique references auth.users (id) on delete set null,
  photo_url  text,
  bio        text not null default '' check (char_length(bio) <= 280),
  is_admin   boolean not null default false,
  updated_at timestamptz not null default now()
);

comment on table public.people is
  'One row per grade member. Rows are seeded from the repo roster, never created by clients.';

-- Keep updated_at honest without letting clients write it.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger people_set_updated_at
  before update on public.people
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Access. Supabase grants everything to anon/authenticated by default; take
-- that back and hand out exactly what the app needs.
-- ---------------------------------------------------------------------------
alter table public.people enable row level security;

revoke all on table public.people from anon, authenticated;
grant select on table public.people to authenticated;
-- Owners may edit only their own profile fields. Column grants stop anyone
-- from touching id, email, owner_uid or is_admin through the API.
grant update (photo_url, bio) on table public.people to authenticated;

create policy "members can read every profile"
  on public.people for select
  to authenticated
  using (true);

create policy "owners can edit their own profile"
  on public.people for update
  to authenticated
  using (owner_uid = auth.uid())
  with check (owner_uid = auth.uid());

-- No insert/delete policies: only the service role (dashboard, seed) can do those.

-- ---------------------------------------------------------------------------
-- Claiming. Runs with the table owner's rights so it can set owner_uid, but
-- only ever links the caller to the row whose email matches their Google
-- account, and only if nobody has claimed it yet. Returns the caller's row,
-- or nothing if their email is not on the roster.
-- ---------------------------------------------------------------------------
create or replace function public.claim_person()
returns setof public.people
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_uid   uuid := auth.uid();
  caller_email text := lower(auth.jwt() ->> 'email');
begin
  if caller_uid is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;

  -- Already claimed by this account.
  if exists (select 1 from public.people where owner_uid = caller_uid) then
    return query select * from public.people where owner_uid = caller_uid;
    return;
  end if;

  -- First login: link the account to the unclaimed row with the same email.
  return query
    update public.people
       set owner_uid = caller_uid
     where lower(email) = caller_email
       and owner_uid is null
     returning *;
end $$;

revoke all on function public.claim_person() from public;
grant execute on function public.claim_person() to authenticated;
